//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchivedTarget
    {
        public int ID { get; set; }
        public int ArchivedSlideRunID { get; set; }
        public int TargetID { get; set; }
    
        public virtual ArchivedSlideRun ArchivedSlideRun { get; set; }
        public virtual Target Target { get; set; }
    }
}
