//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoundReportSection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BoundReportSection()
        {
            this.BoundReportElements = new HashSet<BoundReportElement>();
        }
    
        public int ID { get; set; }
        public int ReportID { get; set; }
        public int ReportSectionID { get; set; }
        public int Sequence { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BoundReportElement> BoundReportElements { get; set; }
        public virtual Report Report { get; set; }
        public virtual ReportSection ReportSection { get; set; }
    }
}
