//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoundReportElement
    {
        public int ID { get; set; }
        public int BoundReportSectionID { get; set; }
        public int ReportElementID { get; set; }
        public int Sequence { get; set; }
        public int Justification { get; set; }
    
        public virtual BoundReportSection BoundReportSection { get; set; }
        public virtual ReportElement ReportElement { get; set; }
    }
}
