//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cassette
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cassette()
        {
            this.Slides = new HashSet<Slide>();
        }
    
        public int ID { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> ScannerID { get; set; }
        public short CassetteStatus { get; set; }
        public Nullable<System.DateTime> ScannerChangeTime { get; set; }
        public bool IsManual { get; set; }
    
        public virtual Scanner Scanner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Slide> Slides { get; set; }
    }
}
