//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepositionShape
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int DepositionAreaID { get; set; }
        public byte[] PolygonPointsInMicron { get; set; }
        public byte[] PolygonPointsInPixel { get; set; }
        public string PolygonPointArrayString { get; set; }
        public Nullable<int> PolygonDpi { get; set; }
        public int OffsetXInMicron { get; set; }
        public int OffsetYInMicron { get; set; }
        public float RotationInDegree { get; set; }
        public Nullable<int> ViewerOffsetXInMicron { get; set; }
        public Nullable<int> ViewerOffsetYInMicron { get; set; }
        public Nullable<float> ViewerRotationInDegree { get; set; }
        public int VisitSequence { get; set; }
        public bool ViewerFlipped { get; set; }
        public byte[] FieldCentersInMicron { get; set; }
    
        public virtual DepositionArea DepositionArea { get; set; }
    }
}
