//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepositionArea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DepositionArea()
        {
            this.DepositionShapes = new HashSet<DepositionShape>();
            this.DepositionAreaMethodAttributeValues = new HashSet<DepositionAreaMethodAttributeValue>();
            this.SlideTypeAssociations = new HashSet<SlideTypeAssociation>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public bool UseAutoFind { get; set; }
        public Nullable<int> BorderFindMethodID { get; set; }
        public int CenterXInMicron { get; set; }
        public int CenterYInMicron { get; set; }
        public int HeightSpanInMicron { get; set; }
        public int WidthSpanInMicron { get; set; }
        public bool AllowEdit { get; set; }
        public bool FindOffsetAndRotation { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> TimeCreated { get; set; }
    
        public virtual BorderFindMethod BorderFindMethod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepositionShape> DepositionShapes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepositionAreaMethodAttributeValue> DepositionAreaMethodAttributeValues { get; set; }
        public virtual IkoUser IkoUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SlideTypeAssociation> SlideTypeAssociations { get; set; }
    }
}
