//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exp_Slide
    {
        public int ID { get; set; }
        public string Barcode { get; set; }
        public string SlideType { get; set; }
        public Nullable<System.DateTime> TimePrepared { get; set; }
        public Nullable<int> NoDP { get; set; }
        public string AppName1 { get; set; }
        public string AppName2 { get; set; }
        public Nullable<int> GenericAppID1 { get; set; }
        public Nullable<int> GenericAppID2 { get; set; }
        public Nullable<int> GenericAppConfigId1 { get; set; }
        public Nullable<int> GenericAppConfigId2 { get; set; }
        public Nullable<int> DepositionAreaID1 { get; set; }
        public Nullable<int> DepositionAreaID2 { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string SpecimenType { get; set; }
        public string Accession { get; set; }
        public string Case { get; set; }
        public string Indication { get; set; }
        public string PatientBarcode { get; set; }
        public string DP1Name { get; set; }
        public string DP2Name { get; set; }
        public string SType { get; set; }
        public Nullable<float> Volume { get; set; }
        public string SampleID { get; set; }
    }
}
