//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Field
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Field()
        {
            this.FieldChannels = new HashSet<FieldChannel>();
            this.OrphanedTargets = new HashSet<OrphanedTarget>();
            this.Targets = new HashSet<Target>();
        }
    
        public int ID { get; set; }
        public int SlideRunAppScanID { get; set; }
        public int FieldLocationXInMicron { get; set; }
        public int FieldLocationYInMicron { get; set; }
        public int NumberOfTargets { get; set; }
        public int NumberOfNuclei { get; set; }
        public int DepositionShapeVisitSequence { get; set; }
        public int VisitSequence { get; set; }
        public Nullable<float> OffsetXInMicron { get; set; }
        public Nullable<float> OffsetYInMicron { get; set; }
        public Nullable<bool> Exclude { get; set; }
    
        public virtual SlideRunAppScan SlideRunAppScan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FieldChannel> FieldChannels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrphanedTarget> OrphanedTargets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Target> Targets { get; set; }
    }
}
