//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldChannel
    {
        public int ID { get; set; }
        public int FieldID { get; set; }
        public int GenericChannelConfigID { get; set; }
        public Nullable<float> ExposureMilliseconds { get; set; }
        public Nullable<float> FocusPositionInMicron { get; set; }
    
        public virtual Field Field { get; set; }
        public virtual GenericChannelConfig GenericChannelConfig { get; set; }
    }
}
