//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenericAppScanConfig
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GenericAppScanConfig()
        {
            this.GenericAppScanConfigMethodAttributeValues = new HashSet<GenericAppScanConfigMethodAttributeValue>();
            this.GenericChannelConfigs = new HashSet<GenericChannelConfig>();
        }
    
        public int ID { get; set; }
        public int GenericAppConfigID { get; set; }
        public int GenericAppScanID { get; set; }
        public int FieldOverLapXInMicron { get; set; }
        public int FieldOverLapYInMicron { get; set; }
        public int AcquisitionBinningMode { get; set; }
        public int NumberOfSlices { get; set; }
        public int CenterSliceOffset { get; set; }
        public int NumberOfTargets { get; set; }
        public int VisitSequenceMethodID { get; set; }
        public bool AllowRepeatScan { get; set; }
        public bool UseMaximizeTargetCountsPerField { get; set; }
        public bool VirtualScan { get; set; }
    
        public virtual GenericAppConfig GenericAppConfig { get; set; }
        public virtual GenericAppScan GenericAppScan { get; set; }
        public virtual GenericAppScan GenericAppScan1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GenericAppScanConfigMethodAttributeValue> GenericAppScanConfigMethodAttributeValues { get; set; }
        public virtual VisitSequenceMethod VisitSequenceMethod { get; set; }
        public virtual VisitSequenceMethod VisitSequenceMethod1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GenericChannelConfig> GenericChannelConfigs { get; set; }
    }
}
