//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenericAppScanStructure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GenericAppScanStructure()
        {
            this.GenericChannelConfigs = new HashSet<GenericChannelConfig>();
        }
    
        public int ID { get; set; }
        public int GenericAppScanID { get; set; }
        public int StructureID { get; set; }
        public int VisitSequence { get; set; }
        public Nullable<bool> IsDisplayedByDefault { get; set; }
    
        public virtual GenericAppScan GenericAppScan { get; set; }
        public virtual Structure Structure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GenericChannelConfig> GenericChannelConfigs { get; set; }
    }
}
