//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenericAppScan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GenericAppScan()
        {
            this.GenericAppScanStructures = new HashSet<GenericAppScanStructure>();
            this.GenericAppScanConfigs = new HashSet<GenericAppScanConfig>();
            this.GenericAppScanConfigs1 = new HashSet<GenericAppScanConfig>();
            this.SlideRunAppScans = new HashSet<SlideRunAppScan>();
        }
    
        public int ID { get; set; }
        public int GenericAppID { get; set; }
        public int ScanLevel { get; set; }
        public float ObjectivePower { get; set; }
        public int PreprocessingMethodID { get; set; }
        public int SlideAdaptationMethodID { get; set; }
        public int TargetSelectionMethodID { get; set; }
        public int ScanAreaRedefiningMethodID { get; set; }
        public int ReOrderFieldVisitSequenceMethodID { get; set; }
        public int BleedThroughCheckMethodID { get; set; }
        public int TargetClassificationMethodID { get; set; }
        public int TargetClassBinningMethodID { get; set; }
        public int StopConditionMethodID { get; set; }
        public int PostProcessingMethodID { get; set; }
        public string LevelName { get; set; }
        public string TargetsName { get; set; }
        public bool MeasureParcentricity { get; set; }
    
        public virtual BleedThroughCheckMethod BleedThroughCheckMethod { get; set; }
        public virtual GenericApp GenericApp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GenericAppScanStructure> GenericAppScanStructures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GenericAppScanConfig> GenericAppScanConfigs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GenericAppScanConfig> GenericAppScanConfigs1 { get; set; }
        public virtual PostprocessingMethod PostprocessingMethod { get; set; }
        public virtual PreprocessingMethod PreprocessingMethod { get; set; }
        public virtual ReorderFieldVisitSequenceMethod ReorderFieldVisitSequenceMethod { get; set; }
        public virtual ScanAreaRedefiningMethod ScanAreaRedefiningMethod { get; set; }
        public virtual SlideAdaptationMethod SlideAdaptationMethod { get; set; }
        public virtual StopConditionMethod StopConditionMethod { get; set; }
        public virtual TargetSelectionMethod TargetSelectionMethod { get; set; }
        public virtual TargetClassificationMethod TargetClassificationMethod { get; set; }
        public virtual TargetClassBinningMethod TargetClassBinningMethod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SlideRunAppScan> SlideRunAppScans { get; set; }
    }
}
