//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IkoLog
    {
        public int ID { get; set; }
        public string LoginID { get; set; }
        public string HostName { get; set; }
        public string UserName { get; set; }
        public string ApplicationName { get; set; }
        public string ApplicationVersion { get; set; }
        public System.DateTime LoginAttempt { get; set; }
        public bool LoginSuccessful { get; set; }
        public Nullable<System.DateTime> LogoutTime { get; set; }
    }
}
