//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IkoUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IkoUser()
        {
            this.AutoExposureMethods = new HashSet<AutoExposureMethod>();
            this.AutoFocusMethods = new HashSet<AutoFocusMethod>();
            this.BleedThroughCheckMethods = new HashSet<BleedThroughCheckMethod>();
            this.BorderFindMethods = new HashSet<BorderFindMethod>();
            this.DepositionAreas = new HashSet<DepositionArea>();
            this.DotCountingMethods = new HashSet<DotCountingMethod>();
            this.FindBestSliceMethods = new HashSet<FindBestSliceMethod>();
            this.GenericAppMethods = new HashSet<GenericAppMethod>();
            this.IkoGroupUsers = new HashSet<IkoGroupUser>();
            this.PostprocessingMethods = new HashSet<PostprocessingMethod>();
            this.PreprocessingMethods = new HashSet<PreprocessingMethod>();
            this.PurgedSlideRuns = new HashSet<PurgedSlideRun>();
            this.ReorderFieldVisitSequenceMethods = new HashSet<ReorderFieldVisitSequenceMethod>();
            this.ScanAreaRedefiningMethods = new HashSet<ScanAreaRedefiningMethod>();
            this.SkipFieldConditionMethods = new HashSet<SkipFieldConditionMethod>();
            this.Slides = new HashSet<Slide>();
            this.SlideAdaptationMethods = new HashSet<SlideAdaptationMethod>();
            this.SlideRuns = new HashSet<SlideRun>();
            this.SlideRunBrightFieldAssociations = new HashSet<SlideRunBrightFieldAssociation>();
            this.SlideRunLocks = new HashSet<SlideRunLock>();
            this.StopConditionMethods = new HashSet<StopConditionMethod>();
            this.StudyUsers = new HashSet<StudyUser>();
            this.TargetClassificationMethods = new HashSet<TargetClassificationMethod>();
            this.TargetClassBinningMethods = new HashSet<TargetClassBinningMethod>();
            this.TargetSelectionMethods = new HashSet<TargetSelectionMethod>();
            this.VisitSequenceMethods = new HashSet<VisitSequenceMethod>();
        }
    
        public int ID { get; set; }
        public string LoginID { get; set; }
        public byte[] Password { get; set; }
        public int Level { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string MiddleName { get; set; }
        public bool NeverExpire { get; set; }
        public bool Disabled { get; set; }
        public long UserRole { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string LastUpdateBy { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoExposureMethod> AutoExposureMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AutoFocusMethod> AutoFocusMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BleedThroughCheckMethod> BleedThroughCheckMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorderFindMethod> BorderFindMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepositionArea> DepositionAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DotCountingMethod> DotCountingMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FindBestSliceMethod> FindBestSliceMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GenericAppMethod> GenericAppMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IkoGroupUser> IkoGroupUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostprocessingMethod> PostprocessingMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreprocessingMethod> PreprocessingMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurgedSlideRun> PurgedSlideRuns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReorderFieldVisitSequenceMethod> ReorderFieldVisitSequenceMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScanAreaRedefiningMethod> ScanAreaRedefiningMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SkipFieldConditionMethod> SkipFieldConditionMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Slide> Slides { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SlideAdaptationMethod> SlideAdaptationMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SlideRun> SlideRuns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SlideRunBrightFieldAssociation> SlideRunBrightFieldAssociations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SlideRunLock> SlideRunLocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StopConditionMethod> StopConditionMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudyUser> StudyUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TargetClassificationMethod> TargetClassificationMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TargetClassBinningMethod> TargetClassBinningMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TargetSelectionMethod> TargetSelectionMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitSequenceMethod> VisitSequenceMethods { get; set; }
    }
}
