//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MethodAttribute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MethodAttribute()
        {
            this.DepositionAreaMethodAttributeValues = new HashSet<DepositionAreaMethodAttributeValue>();
            this.DotCountingMethodAttributeValues = new HashSet<DotCountingMethodAttributeValue>();
            this.GenericAppScanConfigMethodAttributeValues = new HashSet<GenericAppScanConfigMethodAttributeValue>();
            this.GenericChannelConfigMethodAttributeValues = new HashSet<GenericChannelConfigMethodAttributeValue>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepositionAreaMethodAttributeValue> DepositionAreaMethodAttributeValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DotCountingMethodAttributeValue> DotCountingMethodAttributeValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GenericAppScanConfigMethodAttributeValue> GenericAppScanConfigMethodAttributeValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GenericChannelConfigMethodAttributeValue> GenericChannelConfigMethodAttributeValues { get; set; }
    }
}
