//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrphanedTargetChannel
    {
        public int ID { get; set; }
        public int OrphanedTargetID { get; set; }
        public int GenericChannelConfigID { get; set; }
        public byte[] ChannelData { get; set; }
    
        public virtual GenericChannelConfig GenericChannelConfig { get; set; }
        public virtual OrphanedTarget OrphanedTarget { get; set; }
    }
}
