//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Slides = new HashSet<Slide>();
        }
    
        public int ID { get; set; }
        public string Barcode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<byte> Race { get; set; }
        public Nullable<short> Weight { get; set; }
        public Nullable<short> Height { get; set; }
        public Nullable<short> GestationAge { get; set; }
        public Nullable<bool> IsFetusMale { get; set; }
        public Nullable<bool> InsulinDiabetic { get; set; }
        public Nullable<bool> HighFever { get; set; }
        public Nullable<short> PreviousPregnancyCount { get; set; }
        public Nullable<short> PreviousBirthCount { get; set; }
        public Nullable<bool> DownSyndromeHistory { get; set; }
        public string Indication { get; set; }
        public string Accession { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Slide> Slides { get; set; }
    }
}
