//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewedTarget
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReviewedTarget()
        {
            this.ReviewedDotCounts = new HashSet<ReviewedDotCount>();
        }
    
        public int ID { get; set; }
        public int StudyUserID { get; set; }
        public int StudyTargetID { get; set; }
        public int TargetClassificationID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewedDotCount> ReviewedDotCounts { get; set; }
        public virtual StudyUser StudyUser { get; set; }
        public virtual StudyTarget StudyTarget { get; set; }
        public virtual TargetClassification TargetClassification { get; set; }
    }
}
