//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scanner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Scanner()
        {
            this.Cassettes = new HashSet<Cassette>();
            this.SlideRuns = new HashSet<SlideRun>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int ScannerStatus { get; set; }
        public string Configuration { get; set; }
        public Nullable<int> ImageLocationID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cassette> Cassettes { get; set; }
        public virtual ImageLocation ImageLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SlideRun> SlideRuns { get; set; }
    }
}
