//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlideRunBrightField
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SlideRunBrightField()
        {
            this.SlideRunBrightFieldAssociations = new HashSet<SlideRunBrightFieldAssociation>();
        }
    
        public int ID { get; set; }
        public int SlideID { get; set; }
        public int ImageLocationID { get; set; }
        public System.DateTime StartTime { get; set; }
        public float PixelSizeInMicron { get; set; }
        public Nullable<bool> Archived { get; set; }
        public Nullable<bool> Purged { get; set; }
        public bool IsDefault { get; set; }
    
        public virtual ImageLocation ImageLocation { get; set; }
        public virtual Slide Slide { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SlideRunBrightFieldAssociation> SlideRunBrightFieldAssociations { get; set; }
    }
}
