//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlideRunBrightFieldAssociation
    {
        public int ID { get; set; }
        public int SlideRunID { get; set; }
        public int SlideRunBrightFieldID { get; set; }
        public int OffsetXInMicron { get; set; }
        public int OffsetYInMicron { get; set; }
        public float RotationInDegree { get; set; }
        public bool Flipped { get; set; }
        public float Confidence { get; set; }
        public int VisitSequence { get; set; }
        public bool UserAccepted { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> TimeAccepted { get; set; }
    
        public virtual IkoUser IkoUser { get; set; }
        public virtual SlideRun SlideRun { get; set; }
        public virtual SlideRunBrightField SlideRunBrightField { get; set; }
    }
}
