//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlideRunLock
    {
        public int ID { get; set; }
        public int SlideRunID { get; set; }
        public int UserID { get; set; }
        public string MachineName { get; set; }
        public int ProcessID { get; set; }
        public System.DateTime LastWrite { get; set; }
        public System.DateTime LastHeartBeat { get; set; }
    
        public virtual IkoUser IkoUser { get; set; }
        public virtual SlideRun SlideRun { get; set; }
    }
}
