//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slide
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Slide()
        {
            this.SlideAttributeValues = new HashSet<SlideAttributeValue>();
            this.SlideRuns = new HashSet<SlideRun>();
            this.SlideRunBrightFields = new HashSet<SlideRunBrightField>();
        }
    
        public int ID { get; set; }
        public string Barcode { get; set; }
        public Nullable<System.DateTime> TimePrepared { get; set; }
        public int PatientID { get; set; }
        public Nullable<int> CassetteID { get; set; }
        public int UserID { get; set; }
        public int SlideTypeID { get; set; }
        public Nullable<bool> IsBrightField { get; set; }
        public Nullable<int> MatchingSlideID { get; set; }
        public string Accession { get; set; }
        public string CaseNumber { get; set; }
        public Nullable<int> SlideStatusID { get; set; }
        public Nullable<System.DateTime> SlideStatusChangeTime { get; set; }
        public Nullable<int> SampleID { get; set; }
        public Nullable<float> SampleVolumeInMililiters { get; set; }
        public Nullable<int> IkoGroupID { get; set; }
        public string LastUpdateBy { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
    
        public virtual Cassette Cassette { get; set; }
        public virtual IkoGroup IkoGroup { get; set; }
        public virtual IkoUser IkoUser { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Sample Sample { get; set; }
        public virtual SlideStatu SlideStatu { get; set; }
        public virtual SlideType SlideType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SlideAttributeValue> SlideAttributeValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SlideRun> SlideRuns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SlideRunBrightField> SlideRunBrightFields { get; set; }
    }
}
