//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TargetChannel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TargetChannel()
        {
            this.ProbeQcSignals = new HashSet<ProbeQcSignal>();
            this.ReviewedDotCounts = new HashSet<ReviewedDotCount>();
        }
    
        public int ID { get; set; }
        public int TargetID { get; set; }
        public int GenericChannelConfigID { get; set; }
        public int BestFocusedPlane { get; set; }
        public int DotCount { get; set; }
        public bool ConfidentOfCount { get; set; }
        public float Positivity { get; set; }
        public string Clouds { get; set; }
    
        public virtual GenericChannelConfig GenericChannelConfig { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProbeQcSignal> ProbeQcSignals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewedDotCount> ReviewedDotCounts { get; set; }
        public virtual Target Target { get; set; }
    }
}
