//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TargetClassification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TargetClassification()
        {
            this.ReviewedTargets = new HashSet<ReviewedTarget>();
            this.Targets = new HashSet<Target>();
            this.TargetStatistics = new HashSet<TargetStatistic>();
        }
    
        public int ID { get; set; }
        public int TargetClassificationSetID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Abbreviation { get; set; }
        public int SortSequence { get; set; }
        public Nullable<bool> ShowInMenu { get; set; }
        public Nullable<bool> IncludeInCount { get; set; }
        public string Rule { get; set; }
        public int RuleSequence { get; set; }
        public bool IsDefault { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewedTarget> ReviewedTargets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Target> Targets { get; set; }
        public virtual TargetClassificationSet TargetClassificationSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TargetStatistic> TargetStatistics { get; set; }
    }
}
