//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Target
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Target()
        {
            this.ArchivedTargets = new HashSet<ArchivedTarget>();
            this.StudyTargets = new HashSet<StudyTarget>();
            this.Target1 = new HashSet<Target>();
            this.TargetChannels = new HashSet<TargetChannel>();
        }
    
        public int ID { get; set; }
        public int FieldID { get; set; }
        public int TargetLocationXInPixel { get; set; }
        public int TargetLocationYInPixel { get; set; }
        public Nullable<int> ParentTargetID { get; set; }
        public int RegisteredSequence { get; set; }
        public int TargetClassificationID { get; set; }
        public int TargetReviewStatusID { get; set; }
        public bool IsClassificationManual { get; set; }
        public bool Archived { get; set; }
        public bool Hidden { get; set; }
        public bool UserTarget { get; set; }
        public int FusionCount { get; set; }
        public int NuclearSize { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArchivedTarget> ArchivedTargets { get; set; }
        public virtual Field Field { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudyTarget> StudyTargets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Target> Target1 { get; set; }
        public virtual Target Target2 { get; set; }
        public virtual TargetClassification TargetClassification { get; set; }
        public virtual TargetReviewStatu TargetReviewStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TargetChannel> TargetChannels { get; set; }
    }
}
